version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: codeflix-adm-backend
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 3000:3000
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      filebeat_collector: true

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined

  rabbitmq:
    # image: rabbitmq:3.8-management-alpine
    build: ./.docker/rabbitmq
    ports:
      - 15672:15672
    # volumes:
    #   - ./.docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #   - ./.docker/rabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
